#!/usr/bin/env bash

ROOT_COMPAT_GENERATOR_MARKER="Generated by workflow_bundle/workflow/scripts/sync_root_compat.sh"

ROOT_COMPAT_PY_WRAPPERS=(
  "tools/cli.py|workflow_bundle/tools/cli.py"
  "tools/build_final_thesis_docx.py|workflow_bundle/tools/build_final_thesis_docx.py"
  "tools/verify_citation_links.py|workflow_bundle/tools/verify_citation_links.py"
  "tools/postprocess_word_format.py|workflow_bundle/tools/postprocess_word_format.py"
)

ROOT_COMPAT_SH_WRAPPERS=(
  "workflow/scripts/release_preflight.sh|workflow_bundle/workflow/scripts/release_preflight.sh"
  "workflow/scripts/check_workspace.sh|workflow_bundle/workflow/scripts/check_workspace.sh"
  "workflow/scripts/compare_versions.sh|workflow_bundle/workflow/scripts/compare_versions.sh"
  "workflow/scripts/build_release.sh|workflow_bundle/workflow/scripts/build_release.sh"
  "workflow/scripts/postprocess_release.sh|workflow_bundle/workflow/scripts/postprocess_release.sh"
  "workflow/scripts/postprocess_release_linux.sh|workflow_bundle/workflow/scripts/postprocess_release_linux.sh"
  "workflow/scripts/verify_release.sh|workflow_bundle/workflow/scripts/verify_release.sh"
  "workflow/scripts/check_bundle_sync.sh|workflow_bundle/workflow/scripts/check_bundle_sync.sh"
  "workflow/scripts/sync_root_compat.sh|workflow_bundle/workflow/scripts/sync_root_compat.sh"
)
